<a href="https://colab.research.google.com/github/GNuSeekK/ICTCOG/blob/main/2_2_numpy_%EA%B8%B0%EC%B4%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# numpy 모듈 불러오기
import numpy as np

# Numpy의 특징
* numpy는 기본적으로 c언어로 구현되어 있다. - 속도가 빠르다.
* 수치 연산에 관련된 방대한 라이브러리가 존재. ( with scipy )
* 일반 파이썬을 이용한 수치 연산보다 훨씬 빠르다.
* 특히 배열 병렬 연산에 특화 되어

# 1. numpy의 배열 -> ndarray

In [ ]:
# ndarray 만들기
# 1. python의 list를 ndarray화 하기
py_list = [1,2,3]
arr1 = np.array(py_list) # np.array 함수를 이용해서 ndarray 생성 가능
arr1

array([1, 2, 3])

In [ ]:
type(arr1)

numpy.ndarray

In [ ]:
arr1[0], arr1[2]

(1, 3)

## 배열의 종류
1. 스칼라(scalar)
    * 0차원 데이터
    * 특정한 하나의 값
        ```python
        height = 170
        weight = 65
        age = 25
        ```

2. 벡터(vector)
    * 1차원 배열
    * **스칼라가 연속적으로 모여있는 것**
    * 3명의 키를 하나의 배열로 모으기 가능
        ```python
        person_height = [180.1, 173.5, 177.8]
        ```
    * 벡터 내에 데이터가 N개가 있으면 **N차원 벡터**라고 한다.
        * 수학적인 표현

3. 행렬(matrix)
    * 2차원 배열
    * 1차원 배열인 벡터가 여러개 모여있는 것.
        ```python
        person_info = [[180, 25, 68],
                        [170, 35, 70]]
        ```

4. 텐서(tensor)
    * 3차원 이상의 배열
    * 3차원 배열은 2차원 배열이 모여있는 것
    * 4차원 배열은 3차원 배열이 모여있는 것
    * **N차원 배열**을 텐서라고 한다. (N은 3부터는 아니고 0,1,2도 포함)
        - `0 Rank Tensor` : 스칼라
        - `1 Rank Tensor` : 벡터
        - `2 Rank Tensor` : 행렬
        - `3 Rank Tensor` : 3 Rank Tensor
    * Tensorflow란?
        - 구글에서 제공하는 딥러닝 프레임워크
        - 미리 준비된 네트워크에 Tensor를 흘린다.

### 번외 - 프레임워크, 라이브러리, 모듈
프레임워크, 라이브러리, 모듈의 차이점
* 모듈 == 라이브러리 (파이썬에서는 비슷한 개념)
    - 모듈 : 프로그램의 작은 한 조각을 사용할 수 있게 해주는 것
    > 직접 만든 경우 모듈이라고 함
    - 라이브러리 : 이미 만들어진 기능들의 도구 모음
    > 남이 만들면 라이브러리 라고 함.

* 프레임워크
    - 경기장 느낌
    - Tensorflow라는 프레임워크
        * 딥러닝을 손쉽게 구현하기 위한 환경

# numpy 함수 알아보기

## np.arange
* 파이썬의 range함수와 매우 흡사

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

리스트와 배열의 차이

* 리스트는 파이썬에 존재하는 모든 것을 담아낼 수가 있다.
    * list -> ['hello', 10, 10.3, True, 함수]


## 다차원 배열 만들기
2차원 이상의 배열을 다차원 배열이라고 함.
* `np.arange` : 1차원 정수 배열 만들 떄 사용
* `np.zeros` : 0으로 채워진 0 벡터(zero-vector)를 만들 때 사용
* `np.ones` : 1로 채워진 1 벡터(one_vector)를 만들 때 사용

In [ ]:
np.zeros(5) # 5차원 벡터 (1차원 배열) 생성

array([0., 0., 0., 0., 0.])

In [ ]:
# zeros, ones의 매개변수는 텐서의 모양(형상정보 - shape)을 지침
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((3,4,5)) # 3차원 배열 생성, 2차원 배열 3개, 1차원 배열 4개, 0차원 스칼라 5개

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.ones(3) * 5

array([5., 5., 5.])

In [ ]:
np.full((2,3),7)

array([[7, 7, 7],
       [7, 7, 7]])

## 단위 행렬 만들기
* np.eye
* 단위 행렬 : 대각선 방향의 원소가 1이고, 나머지는 0인 행렬

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

## 점구간 만들기 (사잇값 만들기)
* np.linspace

In [ ]:
np.linspace(1, 10, 3)

array([ 1. ,  5.5, 10. ])

In [ ]:
np.linspace(1, 10, 4)

array([ 1.,  4.,  7., 10.])

In [ ]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

## Random을 사용하기 위한 numpy
* 랜덤 배열은 딥러닝에서 매개변수(가중치, 편형)를 초기화 하기 위해서 사용

### np.random.rand
* 완전 랜덤 만들기(정규분포나 균등분포가 아닌 완벽한 랜덤)

In [ ]:
np.random.rand(2,3)

array([[0.04582198, 0.8760902 , 0.66341827],
       [0.89434727, 0.49931583, 0.10240551]])

In [ ]:
np.random.rand(2,3,4)

array([[[0.4961085 , 0.05896324, 0.41679924, 0.33558969],
        [0.70237633, 0.64615608, 0.27208051, 0.74002041],
        [0.56284275, 0.11670831, 0.04646711, 0.87105081]],

       [[0.8794451 , 0.55390658, 0.90710564, 0.6265198 ],
        [0.26771607, 0.76610895, 0.89495181, 0.72810533],
        [0.3905728 , 0.31350595, 0.37301043, 0.33805597]]])

### np.random.randn
* 정규분포 랜덤값 만들기

In [ ]:
np.random.randn(16)

array([ 0.63487867,  0.01197029, -0.91025097, -1.89610885,  2.21625756,
        0.86971511, -1.4156102 ,  0.38608401,  0.36776317, -1.11281666,
       -1.51483357,  0.01034675,  0.19804315,  0.94628614,  0.29525439,
       -1.12059777])

### np.random.uniform
* 균등분포 랜덤값 만들기

In [ ]:
np.random.uniform(1.0,3.0, size=(4,5))

array([[1.07988971, 1.61521916, 1.39243313, 2.64436102, 1.83119576],
       [1.01899138, 1.3843657 , 1.30457838, 1.48070443, 2.87364989],
       [1.3581892 , 1.34111961, 1.9444012 , 2.61119944, 2.61166932],
       [2.03432603, 1.96397244, 1.19470333, 1.38182675, 2.75222661]])

## 정수 랜덤 샘플링 하기
* np.random.choice
* 샘플링 : 전체에서 표본을 추출하는 행위
* 랜덤 샘플링 : 일정한 범위 내에서 필요한 정수를 랜덤으로 추출
* 딥러닝에서는 `mini-batch`를 만들 때 사용

In [ ]:
np.random.choice(10, size= (2,3))

array([[1, 7, 8],
       [5, 2, 1]])

In [ ]:
# 중복 추출 방지
np.random.choice(10, size= (2,3), replace = False)

array([[7, 5, 6],
       [3, 9, 0]])

## 랜덤 정수 배열 만들기
* np.random.randint

In [ ]:
arr1 = np.random.randint(1,100, size= (5,))
arr1

array([30, 49, 37, 51, 35])

In [ ]:
arr2 = np.random.randint(1,100, size= (5,1))
arr2

array([[71],
       [48],
       [31],
       [97],
       [94]])

arr1과 arr2는 같은 배열인가? False
* arr1은 1차원 배열, arr2는 2차원 배열

arr1과 arr2는 같은 **벡터**일까? True
* arr1은 numpy에서는 행벡터의 모양을 하고 있지만, 실제로는 열 벡터이다.
* arr2는 열의 수가 1개의 열벡터 모양을 하고 있다.

대부분의 머신러닝 라이브러리는 기본적인 데이터 취급을 열벡터로 하기 때문에 2차원 배열 이상부터 취급이 가능

# axis 이해하기
axis : 축, 축이란? 데이터가 추가되는 방향의 **인덱스**

예를 들어 3차원 배열 (3,4,5)
* 3차원 배열에 추가되는 건 2차원 배열 -> axis : 0
* 2차원 배열에 추가되는 건 1차원 배열 -> axis : 1
* 1차원 배열에 추가되는 건 0차원 배열 -> axis : 2

In [ ]:
arr = np.arange(1,37).reshape(3,4,3)
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]],

       [[25, 26, 27],
        [28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]]])

In [ ]:
np.max(arr, axis = 0)

# 인덱스와 슬라이싱

In [ ]:
arr = np.arange(1,11).reshape(2,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
arr[0]

array([1, 2, 3, 4, 5])

In [ ]:
arr[0][3]

4

In [ ]:
arr[0,3]

4

특정 차원의 배열을 전체 선택하기 위해서 쓰는 연산자 :

In [ ]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
arr[:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
arr[:,2]

array([3, 8])

In [ ]:
# 3차원, 0차원 제외하고 1, 2차원 데이터 전체를 가지고 오고 싶다.
# 스프레드 연산자( ... )
arr = np.arange(1,37).reshape(3,2,2,3)
arr[0, ... ,0] #3차원과 0차원 사이에 있는 모든 데이터를 선택

array([[ 1,  4],
       [ 7, 10]])

보통 이미지 데이터를 딥러닝에서 사용하고자 할 때 : `{N. W. H. C)`
* `N` : 이미지의 개수
* `H` : 세로 픽셀의 개수
* `W` : 가로 픽셀의 개수
* `C` : 채널수 (컬러 RGB : 3, 흑백 GrayScale :1)

In [ ]:
# 예를 들어 가지고 온 이미지 데이터의 모양이 (60000,28,28,1)
# 이미지가 60,000장
# 이미지의 세로 크기는 28px
# 이미지의 가로 크기는 28px
# 이미지의 채널은 1채널이다.

# 한장의 흑백 이미지를 그릴 때 필요한 정보는 단순하게 세로, 가로 픽셀의 정보만 있으면 된다.
# images[0, ..., 0] -> (28,28)

# 차원수 확장하기
* 보통 딥러닝에서 이미지 분석을 하기 위해 `CNN`알고리즘을 활용
* `CNN`에 필요한 데이터의 형상이 따로 존재하는데, 이 알고리즘을 활용하기 위한 형상(shape)이 존재
* (N, H, W, C)의 형식을 유지해야 한다.
    * `N` : 이미지의 개수(Batch_size)
    * `H` : 세로 픽셀의 개수
    * `W` : 가로 픽셀의 개수
    * `C` : 채널수 (컬러 RGB : 3, 흑백 GrayScale :1)
---
예를 들어 흑백 이미지를 수집 했는데, 이 이미지의 형상 정보(shape)를 확인해 보니 (28,28) 이라면, CNN 알고리즘에 이미지를 집어 넣기 위해서는 (1,28,28,1)의 형태로 만들어 줘야 한다.
* numpy의 np.newaxis
* tensorflow의 tf.newaxis

In [ ]:
arr = np.random.rand(28,28)
arr

array([[4.71107503e-01, 3.50027630e-01, 2.87232838e-02, 4.57455416e-01,
        3.01861193e-02, 7.67951350e-01, 9.54943725e-02, 3.04613233e-01,
        4.48365995e-01, 4.27375201e-01, 4.18709979e-01, 6.55569058e-01,
        4.57301813e-02, 2.64715121e-01, 2.66830959e-01, 4.92449255e-01,
        9.13997044e-01, 3.94944069e-01, 2.94452162e-01, 9.38968605e-01,
        8.92424953e-01, 6.08841606e-01, 7.83298405e-01, 6.17791937e-01,
        8.44867165e-01, 9.57370206e-01, 4.73571730e-01, 7.60340846e-01],
       [7.97111968e-01, 7.47858900e-01, 7.69487126e-01, 3.93184951e-01,
        8.07815716e-01, 2.32723967e-01, 1.20815782e-01, 1.53220627e-02,
        7.42776935e-01, 4.87636318e-01, 6.39353074e-01, 2.16187471e-01,
        3.53912608e-01, 5.99518199e-02, 8.09516764e-01, 6.63062318e-01,
        2.91972370e-01, 3.40123700e-01, 7.36610230e-01, 8.31007297e-01,
        5.75996251e-01, 7.06219624e-01, 6.03857074e-01, 7.38787720e-01,
        6.09149926e-01, 9.98927298e-01, 8.23137310e-01, 3.97438

`(28,28)` 형식의 배열은 `(H,W)`정보만 존재하고 있는 형태 -> '(1,28,28,1) 형태로 만들어 줘야 CNN 레이어에 입력이 가능하다.

In [ ]:
temp_arr = arr[np.newaxis, :, :, np.newaxis]
temp_arr.shape

(1, 28, 28, 1)

In [ ]:
temp_arr = arr[np.newaxis, ..., np.newaxis]
temp_arr.shape

(1, 28, 28, 1)

# 차원 쥐어 짜기
* `np.sqeeze`
* 개수가 1인 차원의 내용을 없애는 기법

In [ ]:
temp_squeeze = np.squeeze(temp_arr)
temp_squeeze.shape

(28, 28)

# 배열의 형상 바꾸기
* `np.newaxis`를 활용하면 축을 하나 추가하게 된다.(차원 수를 늘린다.)
* `np.squeeze`를 활용하면 개수가 1인 차원의 데이터를 삭제(차원 수를 줄인다.)

> 평탄화(flatten) : 2차원 이상의 배열을 1차원 배열로 평평하게 펴주는 역할
* `ravel` : 원본 배열을 평탄화 시킨 **참조**배열을 만들어 낸다. (이를 View 또는 Reference라고 한다.)
* `flatten` : 원본 배열을 평탄화 시킨 **복사된**배열을 만들어 낸다.

ravel은 원본 배열에 수정이 가해질 가능성이 있고, flatten은 원본 배열에 영향을 미치지 않는다.

In [ ]:
x = np.random.randint(15,size=(3,5))
print(x.shape)
print(x)

(3, 5)
[[ 0  7 10  8 13]
 [11  6 10  5  7]
 [ 5  2  7  8 14]]


## ravel 사용

In [ ]:
temp = np.ravel(x)
temp.shape

(15,)

## flatten 사용

In [77]:
temp = np.ndarray.flatten(x)
temp.shape

(15,)

데이터를 안전하게 유지하기 위해 flatten사용

# reshape
배열의 형상을 재구성하는 것

In [78]:
x = np.arange(20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

reshape 팁 : reshape 함수 내의 모든 숫자를 곱했을 때 스칼라 원소의 개수와 같아야 한다.

In [79]:
x.reshape(2,5,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

-1을 사용하면 남은 숫자를 자동으로 계산해 준다.

In [80]:
x.reshape(2, -1, 2) # -1 위치의 값이 알아서 계산된다. 즉 5로 자동 지정됨

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [81]:
# 배열의 스칼라의 개수를 구할 때는 size를 활용
x.size

20

# 브로드캐스팅
* 차언 수가 다른 배열끼리 연산
* 차원이 달라도 0차원 스칼라의 개수가 똑같으면 연산이 가능
* 저차원 배열을 고차원 배열로 **확장**
* 수학적으로 따지게 되면, 고차원 배열의 shape과 똑같은 1벡터(ones)를 만들어서 저차원 배열과 곱한 배ㅕㄹ을 만들어서 계산

In [82]:
x = np.arange(20).reshape(4,5)
y = np.arange(20,40).reshape(4,5)

x.shape, y.shape

((4, 5), (4, 5))

In [84]:
x + y

array([[20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58]])

In [85]:
x * y

array([[  0,  21,  44,  69,  96],
       [125, 156, 189, 224, 261],
       [300, 341, 384, 429, 476],
       [525, 576, 629, 684, 741]])

In [87]:
# shape이 다를 때의 연산
a = np.arange(12).reshape(4,3) # (4,3)
b = np.arange(100,103) #(3,)
c = np.arange(1000,1004) #(4,)
d = b.reshape(1,3) #(1,3)
e = np.arange(0,4).reshape(4,1) # (4,1)


In [88]:
a + b

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [90]:
a + e

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

# 전치행렬 만들기
* 행렬 $A$의 행과 열의 인덱스를 바꾼 것을 전치행렬이라고 한다.
* $A_{(i,j)}$의 인덱스의 위치를$A_{(j,i)}$로 바꾼 것
* Transpose 라고 한다.

In [91]:
A = np.arange(6).reshape(2,3)
A

array([[0, 1, 2],
       [3, 4, 5]])

In [93]:
# ndarray에서 .T만 사용하면 전치행렬을 만들 수 있다.
A.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [102]:
# 벡터의 전치는 가능 할까?
A = np.arange(6)
A.T.shape
# 1차원은 전치가 불가능 하다.

(6,)

In [103]:
A = A[np.newaxis,:]
A.T.shape

(6, 1)