<a href="https://colab.research.google.com/github/GNuSeekK/ICTCOG/blob/main/4_03_%5B%EB%94%A5%EB%9F%AC%EB%8B%9D%5D_%EB%8B%A4%EC%B0%A8%EC%9B%90_%EB%B0%B0%EC%97%B4%EC%9D%98_%EC%97%B0%EC%82%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# 배열의 정보 확인
* `ndim` : 배열의 차원수 알아내기
* `shape` : 배열의 형상 알아내기

In [ ]:
A = np.array([1,2,3,4])
print("A의 차원 : {}".format(A.ndim))
print("A의 형상 : {}".format(A.shape))

A의 차원 : 1
A의 형상 : (4,)


In [ ]:
B = np.array([[1, 2],
              [3, 4],
              [5, 6]])

print("B의 차원 : {}".format(B.ndim))
print("B의 형상 : {}".format(B.shape))

B의 차원 : 2
B의 형상 : (3, 2)


# 행렬의 내적

2차원 배열인 행렬의 내적을 구하는 방법
$$
\begin{pmatrix}
a & b \\
c & d \\
\end{pmatrix}
\cdot
\begin{pmatrix} 
p & q \\
r & s \\
\end{pmatrix}
= \begin{pmatrix} 
ap+br & aq+bs \\
cp+dr & cq+ds \\
\end{pmatrix}
$$

행렬의 내적은
* 왼쪽 행렬의 행(가로)과 오른쪽 행렬의 열(세로)을 원소 별로 곱하고 그 값들을 더한다.
* 계산의 결과가 새로운 다차원 배열의 원소가 된다.

In [ ]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print("A : \n{} / shape : {}".format(A, A.shape))
print()
print("B : \n{} / shape : {}".format(B, B.shape))

A : 
[[1 2]
 [3 4]] / shape : (2, 2)

B : 
[[5 6]
 [7 8]] / shape : (2, 2)


In [ ]:
# np.dot을 이용한 내적
print(np.dot(A, B))
print()
# @ 연산자를 이용한 내적
print(A @ B)

[[19 22]
 [43 50]]

[[19 22]
 [43 50]]


## 행렬 내적의 특징
* 교환 법칙이 성립되지 않는다.
$$
A \cdot B \ne B \cdot A
$$

In [ ]:
print(A @ B)
print()
print(B @ A)

[[19 22]
 [43 50]]

[[23 34]
 [31 46]]


# 행과 열의 개수가 다른 상태에서의 행렬 내적
첫 번째 행렬의 열의 수와 두번째 행렬의 행의 수가 일치하면 내적 가능!
```python
A.shape : (2,3)
B.shape : (3,2)

A @ B 가능
```

```python
A.shape : (2,3)
B.shape : (2,3)

A @ B 불가능
```

In [ ]:
A = np.arange(1,7).reshape(2,3) # 2 × 3 형태의 행렬
B = np.arange(1,7).reshape(3,2) # 3 × 2 형태의 행렬

A.shape, B.shape

((2, 3), (3, 2))

In [ ]:
A @ B

array([[22, 28],
       [49, 64]])

In [ ]:
B.shape, A.shape

((3, 2), (2, 3))

In [ ]:
B @ A

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [ ]:
C = np.arange(1,5).reshape(2,2)

In [ ]:
A.shape, C.shape

((2, 3), (2, 2))

A의 shape은 (2,3), C의 shape은 (2,2) 이기 때문에 내적 불가

In [ ]:
A @ C

ValueError: ignored

In [ ]:
C.shape, A.shape

((2, 2), (2, 3))

In [ ]:
C @ A

array([[ 9, 12, 15],
       [19, 26, 33]])

# 차원 수가 달라도 내적이 가능하다

In [ ]:
A = A.reshape(3, 2)
B = np.array([7,8])

A.shape, B.shape

((3, 2), (2,))

In [ ]:
A @ B

array([23, 53, 83])